=== profK/ApocalypseForge2/ApocalypseForge2/Moves.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Moves">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element name="Move">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Description"> </xs:element>
                            <xs:element name="CriticalFailure">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="1">
                                        <xs:element name="Description"/>
                                        <xs:element name="Options">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element name="Option"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Failure">
                                <xs:complexType>
                                    <xs:all maxOccurs="1">
                                        <xs:element name="Description"/>
                                        <xs:element name="Options">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element name="Option"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="PartialSuccess">
                                <xs:complexType>
                                    <xs:all maxOccurs="1">
                                        <xs:element name="Description"/>
                                        <xs:element name="Options">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element name="Option"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="FullSuccess">
                                <xs:complexType>
                                    <xs:all maxOccurs="1">
                                        <xs:element name="Description"/>
                                        <xs:element name="Options">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element name="Option"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="CriticalSuccess">
                                <xs:complexType>
                                    <xs:all maxOccurs="1">
                                        <xs:element name="Description"/>
                                        <xs:element name="Options">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                  <xs:element name="Option"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Name" type="xs:string" use="required"/>
                        <xs:attribute name="Statistic" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== profK/ApocalypseForge2/ApocalypseForge2/Moves.xml
<?xml version="1.0" encoding="UTF-8"?>
<Moves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="file:/D:/projects/RiderProjects/ApocalypseForge/ApocalypseForge/Moves.xsd">


  <Move Name="Act With Confidence" Statistic="confidence">
    <Description>
      When you attempt to act with confidence, roll confidence
    </Description>
    <CriticalFailure>
      <Description>
        Not only does the actor fail to impress the target of their point of view, but the target thinks they are a phony. The actor has -1D6 to any attempts to convince or manipulate the target of anything until they end of the episode
      </Description>
      <Options>
      </Options>
    </CriticalFailure>
    <Failure>
      <Description>
        The actor totally fails to impress the tagret. Mark an exp on Skills
      </Description>
      <Options>
      </Options>
    </Failure>
    <PartialSuccess>
      <Description>
        The actor has a limited success. The target is swayed by the actor's confidence and the actor the actor takes +1D6 to their next attempt to manipulate or convince the target. However the target may chose one of the following:
      </Description>
      <Options>
        <Option>
          Still uncertain. The actor must add to their argument but take +1D6 to all further attempts to convince the target of this one thing.
        </Option>
        <Option>
          The target thinks the actor is fill of themselves. The actor's +1D6 is nullified and the target takes 2 points of stress from social consequences.
        </Option>
        <Option>
          The target will go along with the target, but they expect a favor down the line. The target gets 1 bond with you
        </Option>
      </Options>
    </PartialSuccess>
    <FullSuccess>
      <Description>
        The actor impresses the target with their confidence. The actor takes +1D6 to their next attempt to manipulate or convince the target.
      </Description>
      <Options>
      </Options>
    </FullSuccess>
    <CriticalSuccess>
      <Description>
        The target accepts the actor as a leader. The actor takes +1D6 to their next attempt to manipulate or convince the target and gains 1 bond with the target.
      </Description>
      <Options>
      </Options>
    </CriticalSuccess>
  </Move>
  <Move Name="Athletic Feat" Statistic="athletics">
    <Description>
      When you attempt a feat of physcial strength, roll athletics
    </Description>
    <CriticalFailure>
      <Description> Actor takes a light harm.
      </Description>
      <Options></Options>
    </CriticalFailure>
    <Failure>
      <Description>Actor takes 2 stress. </Description>
      <Options></Options>
    </Failure>
    <PartialSuccess>
      <Description>Actor succeeds in their action but must also
        choose one of the following</Description>
      <Options>
        <Option>Less than ideal. Actor takes 2 stress</Option>
        <Option>Almost but not quite. Nullify the stress but then
          actor fails in their action</Option>
      </Options>
    </PartialSuccess>
    <FullSuccess>
      <Description>The actor succeeds in the action</Description>
      <Options></Options>
    </FullSuccess>
    <CriticalSuccess>
      <Description>Actor easily succeeds. The Director choose one of the following:</Description>
      <Options>
        <Option>They get two ticks on a clock</Option>
        <Option>They get one tick on a clock but get +1D6 continuing on related actions</Option>
      </Options>
    </CriticalSuccess>
  </Move>
  <Move Name="Avoid Harm" Statistic="athletics">
    <Description>
      *When you try to avoid physical harm, you roll athletics*
    </Description>
    <CriticalFailure>
      <Description>
        Actor takes a severe harm.
      </Description>
      <Options>
      </Options>
    </CriticalFailure>
    <Failure>
      <Description>
        Actor takes a medium harm. Mark an exp on Talents
      </Description>
      <Options>
      </Options>
    </Failure>
    <PartialSuccess>
      <Description>
        Actor takes a light harm. Target may also choose one of the following:
      </Description>
      <Options>
        <Option>
          Reposition. Actor takes -1D6 to their next Harm or Avoid Harm roll
        </Option>
        <Option>
          Weak counter, target takes a light harm
        </Option>
      </Options>
    </PartialSuccess>
    <FullSuccess>
      <Description>
        Actor takes no harm
      </Description>
      <Options>
      </Options>
    </FullSuccess>
    <CriticalSuccess>
      <Description>
        Defense and reposte.  Actor takes no harm. target takes a medium harm.
      </Description>
      <Options>
      </Options>
    </CriticalSuccess>
  </Move>
  <Move Name="Convince " Statistic="manipulation">
    <Description>
      When you attempt to convince someone, roll manipulation.
    </Description>
    <CriticalFailure>
      <Description>
        Not only does the actor fail to convince the target of their point of view, but the targets are now skeptical of anything they say. The actor has -1D6 to any attempts to convince them of anything until they end of the episode
      </Description>
      <Options>
      </Options>
    </CriticalFailure>
    <Failure>
      <Description>
        The actor totally fails to convince the tagret. Mark an exp on Skills
      </Description>
      <Options>
      </Options>
    </Failure>
    <PartialSuccess>
      <Description>
        The actor has a limited success. The target is swayed by the actor's words but can chose one of the following:
      </Description>
      <Options>
        <Option>
          Still uncertain. The actor must add to their argument but take +1D6 to all further attempts to convince the target of this one thing.
        </Option>
        <Option>
          The target rejects the actor's argument argument and take 2 points of stress from cognitive dissonance.
        </Option>
        <Option>
          The target will do or believe as you suggest, but expect a favor down the line. The target gets 1 bond with you
        </Option>
      </Options>
    </PartialSuccess>
    <FullSuccess>
      <Description>
        The target totally buys the actor's argument and should act accordingly.
      </Description>
      <Options>
      </Options>
    </FullSuccess>
    <CriticalSuccess>
      <Description>
        Not only does the target buy the actor's argument, but they look to you for leadership. Take +1 bond with them.
      </Description>
      <Options>
      </Options>
    </CriticalSuccess>
  </Move>
  <Move Name="Creative Leap" Statistic="creativity">
    <Description>Sometimes, logic and reason isn't enough and finding the answers take a gut level intuition. When you want to use your gut, roll creativity</Description>
    <CriticalFailure>
      <Description>You go off on a wild, totally distracting tangent. Take -1D6 to any attempt to gain more information in this scene.</Description>
      <Options></Options>
    </CriticalFailure>
    <Failure>
      <Description>Nah. I got zip.</Description>
      <Options></Options>
    </Failure>
    <PartialSuccess>
      <Description>The actor has limited success. The actor has an idea and a +1 forward to pursue it, but they must choose one of the following:</Description>
      <Options>
        <Option>You're hesitant or embarrassedd to bring it up. Take 2 stress.</Option>
        <Option>Everyone else thinks it's silly or dumb. Take -1d6 to convince them to help you with it.</Option>
        <Option>A person you need to help you follow up is doubtful, you need to give them 1 bond with you to get their aid</Option>
      </Options>
    </PartialSuccess>
    <FullSuccess>
      <Description>Thats not a bad idea! The next person to act on it is at +1 forward
        to follow up.</Description>
      <Options></Options>
    </FullSuccess>
    <CriticalSuccess>
      <Description>That's a great idea! Everyone is at +1 continuing to follow up on it.</Description>
      <Options></Options>
    </CriticalSuccess>
  </Move>
  <Move Name="Difficult Communication" Statistic="communication">
    <Description>
      *When you try to communicate under difficult circumstances, roll communication.*
    </Description>
    <CriticalFailure>
      <Description>
        Not only does the actor fail to communicate but the target gets an incorrect, or even insulting, impression of what the actor ius trying to communicate. The actor loses one bond with the target. If the actor has bonds with the target, they lose one bond with anyone the target chooses who the target has a bond with.
      </Description>
      <Options>
      </Options>
    </CriticalFailure>
    <Failure>
      <Description>
        The actor totally fails to communicate. Mark an exp on Skills
      </Description>
      <Options>
      </Options>
    </Failure>
    <PartialSuccess>
      <Description>
        The actor has limited success. Choose 6 words to communicate what you are trying to say.
      </Description>
      <Options>
      </Options>
    </PartialSuccess>
    <FullSuccess>
      <Description>
        The actor can talk in the clear with the other person. They can ask you questions and you can answer them.
      </Description>
      <Options>
      </Options>
    </FullSuccess>
    <CriticalSuccess>
      <Description>
        Not only the actor talk in the clear like in Full Success but the target also takes +1D6 forward on their next action they take based on your information.
      </Description>
      <Options>
      </Options>
    </CriticalSuccess>
  </Move>
  <Move Name="Express" Statistic="creativity">
    <Description>
      *When you try to express yourself through creation, you roll** ***creativity*****.*
    </Description>
    <CriticalFailure>
      <Description>
